languageCode: en-us
baseURL: "https://codefusionz.com/"
title: Codefusionz
paginate: 5
theme: PaperMod

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

# googleAnalytics: UA-123-45

minify:
  disableXML: true
  minifyOutput: true

params:
  env: production
  title: Codefusionz
  description: "Tech insights for curious minds."
  keywords:
    [
      Blog,
      Portfolio,
      technology,
      programming,
      software,
      development,
      web,
      design,
      designer,
      developer,
      engineer,
      coding,
      code,
      tutorial,
      tutorials,
      programmin,
    ]
  author: Shanmukeshwar
  DateFormat: "January 2, 2006"
  defaultTheme: auto
  disableThemeToggle: false

  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowWordCount: false
  ShowRssButtonInSectionTermList: true
  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: false

  assets:
    favicon: "/favicon/favicon.ico"
    favicon16x16: "/favicon/favicon-16x16"
    favicon32x32: "/favicon/favicon-32x32"
    apple_touch_icon: "/favicon/apple-touch-icon"
    safari_pinned_tab: "/favicon/apple-touch-icon"

  label:
    text: "Codefusionz"
    icon: ""
    iconHeight: 35

  profileMode:
    enabled: true
    title: Welcome to my blog!
    subtitle: Tech insights for curious minds.
    imageUrl: "/images/profile.jpg"
    imageWidth: 120
    imageHeight: 120
    imageTitle: Shanmukeshwar
    buttons:
      - name: Blog
        url: blog
      - name: Projects
        url: projects

  homeInfoParams:
    Title: Codefusionz
    Content: Tech insights for curious minds.

  socialIcons:
    - name: github
      url: "https://github.com/thestackdev"
    - name: linkedin
      url: "https://linkedin.com/in/shanmukeshwar/"
    - name: reddit
      url: "https://reddit.com/user/thestackdev"

  analytics:
    google:
      SiteVerificationTag: "XYZabc"
    bing:
      SiteVerificationTag: "XYZabc"
    yandex:
      SiteVerificationTag: "XYZabc"

  cover:
    hidden: true
    hiddenInList: true
    hiddenInSingle: false

  editPost:
    URL: ""
    Text: ""
    appendFilePath: true

  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]

menu:
  main:
    - identifier: about
      name: About
      url: /about/
      weight: 1
    - identifier: blog
      name: Blog
      url: /blog/
      weight: 2

pygmentsUseClasses: true
markup:
  highlight:
    noClasses: false
    anchorLineNos: true
    codeFences: true
    guessSyntax: true
    lineNos: false
    style: atom-one-dark
